### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yijunyu** [trusted-programming/inlay-hints#2]
# Tasks

- [x] Obtain inlay-hints from `rust-analyzer`
- [x] Insert inlay-hints into source code using `neovim` style
- [x] Reduce the time for loading `rust-analyzer`, improve of processing by 5s per file.
- [x] Parallelize the inlay-hints insertion using the `jwalker` library
- [ ] Insert inlay-hints into source code using `VSCode` style
